services:
  app:
    build:
      context: .
      dockerfile: .docker/prod/Dockerfile
    container_name: fazbear
    volumes:
      - .:/app
      - pnpm_store:/pnpm-store
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/proddb
    networks:
      - prod_network

  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - prod_network

volumes:
  mongo_data:
  pnpm_store:

networks:
  prod_network:
