services:
  app:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    container_name: fazbear
    working_dir: /app
    volumes:
      - .:/app
      - pnpm_store:/pnpm-store
      - /app/node_modules
    command: ["pnpm", "dev"]
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/devdb
    networks:
      - dev_network

  mongo:
    image: mongo:7.0.11
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev_network

volumes:
  mongo_data:
  pnpm_store:

networks:
  dev_network:
