services:
  fazbear:
    build:
      context: .
      dockerfile: .docker/prod/Dockerfile
    container_name: fazbear
    working_dir: /app
    volumes:
      - .:/app
      - pnpm_store:/pnpm-store
      - /app/node_modules
    command: ["pnpm", "start"]
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/devdb
    networks:
      - prod_network

  mongo:
    image: mongo:7.0.11
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - prod_network

volumes:
  mongo_data:
  pnpm_store:

networks:
  prod_network:
